# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi:             ~
    secret:          "%secret%"
    router:
        resource: "%kernel.project_dir%/app/config/routing.yml"
        strict_requirements: ~
        utf8: true
    form:            ~
    csrf_protection: ~
    serializer:      { enable_annotations: true }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # https://symfony.com/doc/5.4/session/database.html#store-sessions-in-a-key-value-database-redis
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_lifetime: 604800 # 7 days
        gc_maxlifetime: 604800 # 7 days
        # Make sure to *NOT* define cookie_samesite, so that it can be changed at runtime
        # https://github.com/coopcycle/coopcycle-web/issues/3084
        # https://github.com/symfony/symfony/issues/45200
        cookie_samesite: ~
        cookie_secure: 'auto'
    fragments:       ~
    http_method_override: true
    assets: ~
    cache:
        prefix_seed: "%env(APP_VERSION)%"
        app: cache.adapter.redis
        default_redis_provider: "snc_redis.default"
        pools:
            twig.cache:
                adapter: cache.app
            s3_flysystem.cache:
                adapter: cache.app
            project.cache:
                adapter: cache.app
            tag_manager.cache:
                adapters:
                  - cache.adapter.array
                  - cache.app
    messenger:
        buses:
            messenger.bus.default:
                # https://symfony.com/doc/current/messenger.html#middleware-for-doctrine
                middleware:
                    # service ids that implement Symfony\Component\Messenger\Middleware\MiddlewareInterface
                    - 'AppBundle\Messenger\RequestIdMiddleware'
                    - 'AppBundle\Messenger\RouteMiddleware'
                    # each time a message is handled, the Doctrine connection
                    # is "pinged" and reconnected if it's closed. Useful
                    # if your workers run for a long time and the database
                    # connection is sometimes lost
                    - doctrine_ping_connection
                    # After handling, the Doctrine connection is closed,
                    # which can free up database connections in a worker,
                    # instead of keeping them open forever
                    - doctrine_close_connection
        transports:
            # https://symfony.com/doc/current/messenger.html#redis-transport
            #
            # When running multiple multiple Redis consumers, you may have error:
            # "Could not acknowledge redis message"
            #
            # This is because each Redis consumer must be unique.
            # Make sure to pass a DSN with a unique consumer name for each process.
            #
            # redis://localhost:6379/<stream>/<group>/<name>
            #
            # https://github.com/symfony/symfony/issues/35358
            # https://github.com/symfony/symfony-docs/pull/11869
            # https://github.com/symfony/symfony-docs/pull/14888
            #
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
        routing:
            'AppBundle\Message\CalculateRoute': async
            'AppBundle\Message\DeliveryCreated': async
            'AppBundle\Message\Email': async
            'AppBundle\Message\PushNotification': async
            'AppBundle\Message\ImportTasks': async
            'AppBundle\Message\OrderReceiptEmail': async
            'AppBundle\Message\Sms': async
            'AppBundle\Message\UpdateLocation': async
            'AppBundle\Message\TopBarNotification': async
            'AppBundle\Message\Webhook': async
            'AppBundle\Message\IndexDeliveries': async
            'AppBundle\Message\WoopitDocumentWebhook': async
            'AppBundle\Message\ImportDeliveries': async
            'AppBundle\Message\CalculateTaskDistance': async
    workflows:
        enabled: true
    mailer:
        dsn: '%env(COOPCYCLE_MAIL_URL)%'
    http_client:
        scoped_clients:
            urbantz.client:
                base_uri: 'https://api.urbantz.com/v2/'
                headers:
                    X-Api-Key: '%env(URBANTZ_API_KEY)%'
            facebook.client:
                base_uri: 'https://graph.facebook.com/'
            browserless.client:
                base_uri: "%env(COOPCYCLE_BROWSERLESS_HOST)%"
            mjml.client:
                base_uri: "%env(COOPCYCLE_MJML_HOST)%/"
            vroom.client:
                base_uri: "http://%env(VROOM_HOST)%/"
            api.client:
                base_uri: "%router.request_context.scheme%://%router.request_context.host%"
            osrm.client:
                base_uri: "http://%osrm_host%"
                timeout: 5.0
            cubejs.client:
                base_uri: "%env(CUBEJS_API_URL)%/"
            woopit.http_client:
                base_uri: '%env(WOOPIT_CARRIER_API_URL)%/'
                headers:
                    X-Api-Version: '%env(WOOPIT_API_VERSION)%'
            dabba.client:
                base_uri: "%env(DABBA_BASE_URL)%/"
            umap.client:
                base_uri: "https://umap.openstreetmap.fr/"
            unsplash.client:
                base_uri: "https://api.unsplash.com/"
                headers:
                    Authorization: 'Client-ID %env(UNSPLASH_ACCESS_KEY)%'
            pixabay.client:
                base_uri: "https://pixabay.com/api/"
                query:
                    key: "%env(PIXABAY_API_KEY)%"
            edenredsynchronizer.client:
                base_uri: "%env(EDENRED_SYNCHRONIZER_BASE_URL)%"
                query:
                    api_key: "%env(EDENRED_SYNCHRONIZER_API_KEY)%"
            insee.client:
                base_uri: "https://api.insee.fr/api-sirene/3.11/"
                headers:
                    X-INSEE-Api-Key-Integration: '%env(INSEE_PORTAIL_API_KEY)%'

knp_paginator:
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'

sonata_seo:
    encoding: UTF-8
    page:
        title: CoopCycle
        metas:
            name:
                robots: index, follow
            http-equiv:
                'Content-Type': text/html; charset=utf-8
            charset:
                UTF-8: ''

command_bus:
    middlewares:
        logger: true

event_bus:
    event_name_resolver_strategy: named_message
    logging: ~

mjml:
    renderer: 'service'
    options:
        service_id: 'AppBundle\Mjml\MjmlServerRenderer'

kreait_firebase:
    projects:
        coopcycle:
            credentials: '%env(FIREBASE_CREDENTIALS)%'

sylius_taxation:
    resources:
        tax_category:
            classes:
                model: AppBundle\Entity\Sylius\TaxCategory
        tax_rate:
            classes:
                model: AppBundle\Entity\Sylius\TaxRate

sylius_order:
    resources:
        order:
            classes:
                model: AppBundle\Entity\Sylius\Order
                repository: AppBundle\Entity\Sylius\OrderRepository
        order_item:
            classes:
                model: AppBundle\Entity\Sylius\OrderItem
                repository: AppBundle\Entity\Sylius\OrderItemRepository

sylius_product:
    resources:
        product:
            classes:
                model: AppBundle\Entity\Sylius\Product
                repository: AppBundle\Entity\Sylius\ProductRepository
        product_variant:
            classes:
                model: AppBundle\Entity\Sylius\ProductVariant
        product_option:
            classes:
                model: AppBundle\Entity\Sylius\ProductOption
        product_option_value:
            classes:
                model: AppBundle\Entity\Sylius\ProductOptionValue

sylius_taxonomy:
    resources:
        taxon:
            classes:
                model: AppBundle\Entity\Sylius\Taxon
                repository: AppBundle\Entity\Sylius\TaxonRepository

sylius_customer:
    resources:
        customer:
            classes:
                model: AppBundle\Entity\Sylius\Customer

sylius_locale:
    locale: "%locale%"

sylius_currency:
    driver: doctrine/orm

sylius_promotion:
    resources:
        promotion_subject:
            classes:
                model: AppBundle\Entity\Sylius\Order
        promotion_coupon:
            classes:
                model: AppBundle\Entity\Sylius\PromotionCoupon

sylius_payment:
    resources:
        payment:
            classes:
                model: AppBundle\Entity\Sylius\Payment
        payment_method:
            classes:
                repository: Sylius\Bundle\PaymentBundle\Doctrine\ORM\PaymentMethodRepository