services:

  _defaults:
    autowire: false
    autoconfigure: false
    public: true

  coopcycle.domain.order.reactor.create_tasks:
    class: AppBundle\Domain\Order\Reactor\CreateTasks
    arguments:
      - '@coopcycle.delivery.manager'
      - '@coopcycle.utils.order_text_encoder'
    tags:
        - name: event_subscriber
          subscribes_to: order:accepted

  AppBundle\Domain\Order\Reactor\CreateTasks: '@coopcycle.domain.order.reactor.create_tasks'

  coopcycle.domain.order.reactor.cancel_tasks:
    class: AppBundle\Domain\Order\Reactor\CancelTasks
    arguments:
      - '@coopcycle.task_manager'
    tags:
        - name: event_subscriber
          subscribes_to: order:cancelled
        - name: event_subscriber
          subscribes_to: order:refused

  coopcycle.domain.order.reactor.calculate_timeline:
    class: AppBundle\Domain\Order\Reactor\CalculateTimeline
    arguments:
      - '@coopcycle.order_timeline_calculator'
      - '@event_bus'
    tags:
        - name: event_subscriber
          subscribes_to: order:created
        - name: event_subscriber
          subscribes_to: order:delayed
        - name: event_subscriber
          subscribes_to: order:picked
        - name: event_subscriber
          subscribes_to: order:dropped

  coopcycle.domain.order.reactor.send_email:
    class: AppBundle\Domain\Order\Reactor\SendEmail
    arguments:
      - '@coopcycle.email_manager'
      - '@coopcycle.settings_manager'
      - '@event_bus'
      - '@Symfony\Component\Messenger\MessageBusInterface'
      - '@AppBundle\Service\NotificationPreferences'
    tags:
        - name: event_subscriber
          subscribes_to: order:created
        - name: event_subscriber
          subscribes_to: order:accepted
        - name: event_subscriber
          subscribes_to: order:refused
        - name: event_subscriber
          subscribes_to: order:cancelled
        - name: event_subscriber
          subscribes_to: order:delayed
        - name: event_subscriber
          subscribes_to: order:fulfilled

  coopcycle.domain.order.reactor.send_remote_push_notification:
    class: AppBundle\Domain\Order\Reactor\SendRemotePushNotification
    autowire: true
    arguments:
      $userManager: '@coopcycle.user_manager'
    tags:
        - name: event_subscriber
          subscribes_to: order:created
        - name: event_subscriber
          subscribes_to: order:accepted
        - name: event_subscriber
          subscribes_to: order:state_changed

  coopcycle.domain.order.reactor.clear_session:
    class: AppBundle\Domain\Order\Reactor\ClearSession
    arguments:
      - '@AppBundle\Sylius\Cart\SessionStorage'
    tags:
        - name: event_subscriber
          subscribes_to: order:checkout_succeeded

  coopcycle.domain.order.reactor.capture_payment:
    class: AppBundle\Domain\Order\Reactor\CapturePayment
    arguments:
      - '@AppBundle\Payment\Gateway'
      - '@logger'
    tags:
        - name: event_subscriber
          subscribes_to: order:fulfilled
        - name: event_subscriber
          subscribes_to: order:cancelled

  coopcycle.domain.order.reactor.add_customer_address:
    class: AppBundle\Domain\Order\Reactor\AddCustomerAddress
    tags:
        - name: event_subscriber
          subscribes_to: order:created

  coopcycle.domain.order.reactor.enhance_shipping_address:
    class: AppBundle\Domain\Order\Reactor\EnhanceShippingAddress
    arguments:
      - '@libphonenumber\PhoneNumberUtil'
    tags:
        - name: event_subscriber
          subscribes_to: order:created

  coopcycle.domain.order.reactor.publish_live_update:
    class: AppBundle\Domain\Order\Reactor\PublishLiveUpdate
    arguments:
      - '@AppBundle\Service\LiveUpdates'
    tags:
        - name: event_subscriber
          subscribes_to: order:created
        - name: event_subscriber
          subscribes_to: order:accepted
        - name: event_subscriber
          subscribes_to: order:refused
        - name: event_subscriber
          subscribes_to: order:delayed
        - name: event_subscriber
          subscribes_to: order:cancelled
        - name: event_subscriber
          subscribes_to: order:picked
        - name: event_subscriber
          subscribes_to: order:dropped
        - name: event_subscriber
          subscribes_to: order:fulfilled
        - name: event_subscriber
          subscribes_to: order:updated
        - name: event_subscriber
          subscribes_to: order:state_changed

  coopcycle.domain.order.reactor.modify_promotions_usage:
    class: AppBundle\Domain\Order\Reactor\ModifyPromotionsUsage
    arguments:
      - '@AppBundle\Service\LiveUpdates'
    tags:
        - name: event_subscriber
          subscribes_to: order:created
        - name: event_subscriber
          subscribes_to: order:cancelled

  coopcycle.domain.order.reactor.trade_dabba:
    class: AppBundle\Domain\Order\Reactor\TradeDabba
    arguments:
      - '@AppBundle\Dabba\Client'
      - '@monolog.logger.dabba'
    tags:
        - name: event_subscriber
          subscribes_to: order:picked

  coopcycle.domain.order.reactor.create_geofencing_channel:
    class: AppBundle\Domain\Order\Reactor\CreateGeofencingChannel
    arguments:
      $geofencing: '@AppBundle\Service\Geofencing'
    tags:
        - name: event_subscriber
          subscribes_to: order:picked

  coopcycle.domain.order.reactor.delete_geofencing_channel:
    class: AppBundle\Domain\Order\Reactor\DeleteGeofencingChannel
    arguments:
      $geofencing: '@AppBundle\Service\Geofencing'
    tags:
        - name: event_subscriber
          subscribes_to: order:dropped
        - name: event_subscriber
          subscribes_to: order:cancelled

  # WARNING
  # Event subscribers are registered using the same order as they are declared in this file.
  # The "priority" attribute has no effect.
  # The reactor to update state *MUST* be registered last in the chain.
  # @see https://github.com/SimpleBus/SimpleBus/blob/master/Bundle/SymfonyBridge/src/DependencyInjection/Compiler/RegisterSubscribers.php
  coopcycle.domain.order.reactor.update_state:
    class: AppBundle\Domain\Order\Reactor\UpdateState
    arguments:
      - '@sm.factory'
      - '@sylius.order_processing.order_payment_processor'
      - '@event_bus'
      - '@AppBundle\Utils\OrderTimeHelper'
    tags:
        - name: event_subscriber
          subscribes_to: order:created
        - name: event_subscriber
          subscribes_to: order:accepted
        - name: event_subscriber
          subscribes_to: order:refused
        - name: event_subscriber
          subscribes_to: order:cancelled
        - name: event_subscriber
          subscribes_to: order:fulfilled
        - name: event_subscriber
          subscribes_to: order:preparation_started
        - name: event_subscriber
          subscribes_to: order:preparation_finished
        - name: event_subscriber
          subscribes_to: order:restored
        - name: event_subscriber
          subscribes_to: order:checkout_succeeded
        - name: event_subscriber
          subscribes_to: order:checkout_failed

  coopcycle.domain.order.reactor.cancel_edenred_transaction:
    class: AppBundle\Domain\Order\Reactor\CancelEdenredTransaction
    arguments:
      - '@AppBundle\Edenred\Client'
      - '@sm.factory'
    tags:
        - name: event_subscriber
          subscribes_to: order:refused
        - name: event_subscriber
          subscribes_to: order:cancelled

  coopcycle.domain.order.reactor.trigger_webhook:
    class: AppBundle\Domain\Order\Reactor\TriggerWebhook
    arguments:
      - '@messenger.default_bus'
      - '@api_platform.iri_converter'
    tags:
      - name: event_subscriber
        subscribes_to: order:created

  coopcycle.domain.order.reactor.orders_rate_limit:
    class: AppBundle\Domain\Order\Reactor\OrdersRateLimitReactor
    arguments:
      - '@AppBundle\Utils\OrdersRateLimit'
    tags:
      - name: event_subscriber
        subscribes_to: order:created
      - name: event_subscriber
        subscribes_to: order:delayed
      - name: event_subscriber
        subscribes_to: order:picked
      - name: event_subscriber
        subscribes_to: order:refused
      - name: event_subscriber
        subscribes_to: order:cancelled

  coopcycle.domain.order.reactor.auto_accept_order:
    class: AppBundle\Domain\Order\Reactor\AutoAcceptOrder
    autowire: true
    tags:
      - name: event_subscriber
        subscribes_to: order:created

  coopcycle.domain.order.reactor.create_impec_order:
    class: AppBundle\Domain\Order\Reactor\CreateLoopeatOrder
    arguments:
      - '@AppBundle\LoopEat\Client'
    tags:
      - name: event_subscriber
        subscribes_to: order:created

  coopcycle.domain.order.reactor.validate_impec_order:
    class: AppBundle\Domain\Order\Reactor\ValidateLoopeatOrder
    arguments:
      - '@AppBundle\LoopEat\Client'
    tags:
      - name: event_subscriber
        subscribes_to: order:picked

  coopcycle.domain.order.reactor.finish_impec_order:
    class: AppBundle\Domain\Order\Reactor\FinishLoopeatOrder
    arguments:
      - '@AppBundle\LoopEat\Client'
    tags:
      - name: event_subscriber
        subscribes_to: order:fulfilled
