parameters:
    tile38_fleet_key: '%database_name%_test:fleet'
    tile38_doorstep_chan_namespace: '%database_name%_test'
    typesense_shops_collection_name: "shops_test"
    typesense_products_collection_name: "products_test"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Tests\Behat\:
    #     resource: '../tests/Behat/*'

    # Tests\Behat\JsonContext:
    #     arguments:
    #         $httpCallResultPool: '@behatch.http_call.result_pool'
