name: Test
on: push
env:
  APP_ENV: test
  NODE_ENV: test
jobs:
  BASE:
    name: Run PHP unit tests
    runs-on: ubuntu-latest
    env:
      STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    steps:
      - name: Run CoopCycle Web
        uses: .github/actions/run-coopcycle-web
      - name: Run PHPUnit
        run: |
          cp phpunit.xml.dist phpunit.xml
          docker compose exec -T php vendor/bin/phpunit
